### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by wafflemelon** [ry00001/Tuxedo#21]
- [ ] Clean up 
- [x] Add more useful features
- [ ] Improve Audio with the ongoing DSP
- [x] New help command (dynamic)
- [x] Good and functional website
- [ ] Note module (Ry)
- [ ] Fix prefixes (Ry)

**Comment by perryprog** [comment]
Would you mind changing that to a checked list? like so:
```
- [ ] item one
- [x] checked item
```

**Comment by wafflemelon** [comment]
It's just a suggestion list, need approval from ry else meeeeeh

**Comment by perryprog** [comment]
Yeah, it just adds a nice little progress bar on the issue. Also, you forgot a space after each `[ ]`.

**Comment by ry00001** [comment]
henlo i am ry and i approve of this message @wafflemelon @perryprog

**Comment by wafflemelon** [comment]
I'll start working from tomorrow

**Comment by wafflemelon** [comment]
Should I work on a redis version of erio? It would be great if people wanna host it on their android phones.

**Comment by ry00001** [comment]
@wafflemelon go ahead if you want but make it a separate branch

**Comment by LewisTehMinerz** [comment]
also, we should either use trello or the projects feature for this type of thing.

**Comment by ry00001** [comment]
@perryprog @wafflemelon @LewisTehMinerz https://trello.com/b/lWj2BO6k/erio

psssst we have a trello now

tell me your trello usernames

**Comment by perryprog** [comment]
perryprog

**Comment by wafflemelon** [comment]
Don't have a Trello also what is the support invite

**Comment by ry00001** [comment]
Tuxedo legacy is dead. Archiving repo and closing issue.
